###############################################################
#   Parking P023 â€“ Standalone Simulation + Digital Twin YAML
###############################################################

seed: 42
runs: 1

arrival_mode: dataset
dataset_path: data/P023_sim/dataset_P023_simready_updated.csv

twin_train_start: "2022-01-01"
twin_train_end:   "2022-05-31"

twin_test_start:  "2022-06-01"
twin_test_end:    "2022-06-30"

###############################################################
# DYNAMIC PRICING POLICY (CALIBRATED)
###############################################################
policy: dynpricing

target: 0.75       # antes 0.95
k: 0.4              # antes 0.5
p_min: 1.45          # antes 1.0
p_max: 3.0
interval: 20        # antes 10

###############################################################
# LOT CONFIGURATION
###############################################################
lots:
  - name: P023
    type: commuter
    capacity: 180
    price: 1.5
    distance: 1.0
    ev_spots: 0
    chargers: 0

###############################################################
# ELASTICITIES (CALIBRATED)
###############################################################
elasticity:
  price: 2.0        
  traffic: 0.3
  exit_friction: 1.0

###############################################################
# EV CONFIG
###############################################################
ev_share: 0.0
power_rate_kW: 7
battery_init_mean: 0.4
battery_target: 0.8
battery_capacity_kWh: 50
price_per_kWh: 0.25

max_wait: 1
debug: false

event_calendar:
  - day: 160
    lot: P023
    start_hour: 18.0
    end_hour: 23.0
    demand_uplift: 1.5
    price_multiplier: 1.2
